//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthoApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> IdPen { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Custumer Custumer { get; set; }
        public virtual Pen Pen { get; set; }
    }
}
